project:
  type: website
  output-dir: docs
website:
  title: "blog"
  twitter-card: true
  navbar:
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: Archive
        href: archive.qmd
      - about.qmd
site:
  baseurl: "/<oskarymd.github.io>"
 
      
format:
  html:
    theme: sketchy
    css: styles.css
    code-fold: true

  



